export { default as banner1 } from './Banner_1.png';
export { default as banner2 } from './Banner_2.png';
export { default as banner3 } from './Banner_3.png';
export { default as banner4 } from './Banner_4.png';
export { default as banner5 } from './Banner_5.png';
export { default as banner6 } from './Banner_6.png';
export { default as banner7 } from './Banner_7.png';
export { default as banner13 } from './Banner_13.png';
export { default as banner14 } from './Banner_14.png';
